[project]
name = "chinhook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ollama>=0.6.2",
    "openai>=3.16.2",
    "pandas>=3.0.6",
    "psycopg2>=2.9.13",
    "python-dotenv>=1.2.3",
    "qdrant-client>=1.19.1",
    "sqlalchemy>=2.0.54",
    "sqlglot>=30.19.0",
]
