[theme]
primaryColor = "#B11813"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A1A1A"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
